name: Send Asia Market Digest

on:
  schedule:
    # 08:00 Asia/Jakarta → 01:00 UTC
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  send-mail:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run news mailer (Asia Market)
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
          TOPIC_QUERIES: ${{ vars.ASIA_TOPIC_QUERIES }}
          REGION: "Asia"
          EMAIL_FROM: ${{ vars.EMAIL_FROM }}
          EMAIL_TO: ${{ vars.EMAIL_TO }}
        run: python -m src.news_mailer.main
