name: Send Europe Market Digest

on:
  schedule:
    # 15:00 Asia/Jakarta → 08:00 UTC
    - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  send-mail:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run news mailer (Europe Market)
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
          BREVO_API_KEY: ${{ secrets.BREVO_API_KEY }}
          BREVO_EMAIL_PROVIDER: ${{ secrets.BREVO_EMAIL_PROVIDER }}
          TOPIC_QUERIES: ${{ vars.EUROPE_TOPIC_QUERIES }}
          REGION: "Europe"
          EMAIL_FROM: ${{ vars.EMAIL_FROM }}
          EMAIL_TO: ${{ vars.EMAIL_TO }}
        run: python -m src.news_mailer.main
