name: Send News Digest

# Triggers at 08:00, 12:00, 16:00, and 20:00 Asia/Jakarta time (UTC+7)
on:
  schedule:
    # GitHub Actions schedules use UTC. 08,12,16,20 UTC+7 → 01,05,09,13 UTC.
    - cron: "0 1 * * *"
    - cron: "0 5 * * *"
    - cron: "0 9 * * *"
    - cron: "0 13 * * *"
  # Manual trigger
  workflow_dispatch:

jobs:
  send-mail:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run news mailer
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
        run: python -m src.news_mailer.main
